### PR TITLE
CP-121: Django 1.9 Upgrade (backwards compatible changes) 

### PR DESCRIPTION
**Pull request by linseyray**
See an overview of the changes [here] (https://github.com/vikingco/mvne-platform/pull/4776).

### CODE REVIEW

**Comment by Duologic** [comment]
@linseyray Have you considered using the upstream version of this? It claims to work with Django 1.9.

**Comment by linseyray** [comment]
Nice catch @Duologic! I didn't notice. I looked into it but it seems we haven't pulled in their changes since the fork was made back in 2012, so it might cause more headache than it would help. I also didn't spot changes in their commit for 1.9 support that haven't been covered by these pull requests, so it's probably safest to stick with them. [This one](https://github.com/vikingco/django-comments-xtd/pull/6) covers all the changes.

**Comment by Duologic** [comment]
And this one will remove this as a dependency: https://github.com/vikingco/mvne-platform/pull/5097 :)

**Comment by linseyray** [comment]
Ah yes, I noticed the dependency cleanup... extra fun! :')

**Comment by linseyray** [comment]
Moved into mvne-platform. Changes have become redundant (said code was removed in the process).

**Pull request closed without merging**
